version: '3.8'
services:
  db:
    image: postgres:16
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-docker
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: redis
    ports:
      - 6379:6379

  app:
    build:
      context: .
    container_name: fastapi_app_task_and_users
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env-docker
    command: ['/task_and_users/docker/app.sh']
    ports:
      - 7777:8000

volumes:
  postgres_data: